<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
<script>
    /* try catch 语法： 是捕捉try部分的异常，当你没有try catch的时候，如果出现异常则程序报错，加上try catch，出现异常程序正常运行，只是把错误信息存储到Exception里，所以catch是用来提取异常信息的，
    *
    *
    * */

    try{
        console.log(a);           //代码区
    }catch(e){
        console.log(e.ERROR);     //异常处理
    }finally{
        console.log('kk')          //代码区   一定会执行的代码区  不会因为异常的出现终止
    }

    var utils = {
        listToArray : function (similarAry){
            var ary = [];
            try {
                ary =  ary.slice.call(similarAry)
            }catch(e){
                for(var i=0; i<similarAry.length; i++){
                    ary[ary.length] = similarAry[i];
                }
            }
            return ary;
        }
    }
</script>